export type MassCompetitorCategory =
  | 'workflow-automation'
  | 'agent-builder'
  | 'coding-agent'
  | 'research-knowledge'
  | 'observability-evals'
  | 'product-ops';

export type MassCompetitor = {
  id: string;
  name: string;
  category: MassCompetitorCategory;
  priority: 'copy-now' | 'study' | 'watch';
  url: string;
  repo?: string;
  plainEnglish: string;
  whyItMatters: string;
  copy: string;
  avoid: string;
  mazosMove: string;
  loopPack: string;
};

export type MassCompetitorGroup = {
  category: MassCompetitorCategory;
  label: string;
  simpleRead: string;
  competitors: MassCompetitor[];
};

export type MassCompetitorCatalog = {
  generatedAt: string;
  sourceRule: string;
  total: number;
  copyNow: number;
  groups: MassCompetitorGroup[];
  topMoves: string[];
};

const CATEGORY_COPY: Record<MassCompetitorCategory, { label: string; simpleRead: string }> = {
  'workflow-automation': {
    label: 'Workflow automation',
    simpleRead: 'Tools that turn triggers, connectors, approvals, and histories into repeatable work.',
  },
  'agent-builder': {
    label: 'Agent builders and runtimes',
    simpleRead: 'Tools that package prompts, tools, memory, state, and human review into agentic apps.',
  },
  'coding-agent': {
    label: 'Coding agents',
    simpleRead: 'Tools that turn tasks into code changes with files, shell, browser, branches, and review artifacts.',
  },
  'research-knowledge': {
    label: 'Research and knowledge',
    simpleRead: 'Tools that ingest sources, answer with citations, and turn notes into decisions.',
  },
  'observability-evals': {
    label: 'Observability and evals',
    simpleRead: 'Tools that prove AI runs are useful, traceable, cheaper, safer, and improving over time.',
  },
  'product-ops': {
    label: 'Product operations',
    simpleRead: 'Tools that keep product teams clear on priorities, decisions, docs, delivery, and customer signal.',
  },
};

export const MASS_COMPETITORS: MassCompetitor[] = [
  {
    id: 'n8n',
    name: 'n8n',
    category: 'workflow-automation',
    priority: 'copy-now',
    url: 'https://n8n.io/',
    repo: 'n8n-io/n8n',
    plainEnglish: 'A visual automation builder for connecting apps, triggers, and AI steps.',
    whyItMatters: 'It makes complex workflows feel inspectable because every run has nodes, inputs, outputs, and errors.',
    copy: 'Run history, node debugging, templates, trigger catalog, and visible failure states.',
    avoid: 'A blank-canvas connector maze before MAZos has first-class loop receipts.',
    mazosMove: 'Turn Loop Receipts into a Run Inspector with step-by-step evidence.',
    loopPack: 'Run Inspector',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'workflow-automation',
    priority: 'study',
    url: 'https://zapier.com/',
    plainEnglish: 'A mainstream automation product for connecting SaaS tools without code.',
    whyItMatters: 'It proves that normal users buy clear triggers, actions, templates, and reliability more than raw power.',
    copy: 'Simple trigger/action language, large template library, and plain failure recovery.',
    avoid: 'Selling integration count as the core promise.',
    mazosMove: 'Describe loops as simple triggers, checks, approvals, and outcomes.',
    loopPack: 'Connector Policy',
  },
  {
    id: 'make',
    name: 'Make',
    category: 'workflow-automation',
    priority: 'study',
    url: 'https://www.make.com/',
    plainEnglish: 'A scenario-based automation builder with a visual canvas.',
    whyItMatters: 'It shows how branching, retries, and modules can be understandable without becoming an IDE.',
    copy: 'Scenario view, module status, scheduling, branching, and execution replay.',
    avoid: 'Overdesigned visual diagrams for loops that only need a compact timeline.',
    mazosMove: 'Add a compact loop timeline before adding a full canvas.',
    loopPack: 'Loop Timeline',
  },
  {
    id: 'activepieces',
    name: 'Activepieces',
    category: 'workflow-automation',
    priority: 'copy-now',
    url: 'https://www.activepieces.com/',
    repo: 'activepieces/activepieces',
    plainEnglish: 'An open-source automation builder with connectors, flows, and AI pieces.',
    whyItMatters: 'It has a practical open-source shape for connectors, permissions, approvals, and flow templates.',
    copy: 'Human approval steps, connector metadata, flow test runs, and self-hosting posture.',
    avoid: 'Treating every connector as equally important.',
    mazosMove: 'Rank connectors by local usefulness and permission risk.',
    loopPack: 'Connector Policy',
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    category: 'workflow-automation',
    priority: 'study',
    url: 'https://pipedream.com/',
    plainEnglish: 'A developer-friendly workflow platform mixing code steps and integrations.',
    whyItMatters: 'It is strong at fast event handling, logs, secrets, and developer ergonomics.',
    copy: 'Event sources, code steps, logs, env handling, and quick test loops.',
    avoid: 'Making MAZos feel like a cloud function editor.',
    mazosMove: 'Expose simple test inputs and logs for each loop run.',
    loopPack: 'Runtime Export',
  },
  {
    id: 'windmill',
    name: 'Windmill',
    category: 'workflow-automation',
    priority: 'study',
    url: 'https://www.windmill.dev/',
    repo: 'windmill-labs/windmill',
    plainEnglish: 'An open-source platform for scripts, workflows, internal tools, and approvals.',
    whyItMatters: 'It blends code, scheduled jobs, approvals, and internal app surfaces in a practical way.',
    copy: 'Script history, approval gates, scheduled jobs, and lightweight internal apps.',
    avoid: 'Letting internal tooling sprawl hide the main MAZos decision loop.',
    mazosMove: 'Make every loop show owner, cadence, approval gate, and latest useful result.',
    loopPack: 'Cadence Controller',
  },
  {
    id: 'node-red',
    name: 'Node-RED',
    category: 'workflow-automation',
    priority: 'watch',
    url: 'https://nodered.org/',
    repo: 'node-red/node-red',
    plainEnglish: 'A flow-based programming tool often used for IoT and event wiring.',
    whyItMatters: 'It proves visual wiring can work when nodes are small and runtime feedback is immediate.',
    copy: 'Small node vocabulary and clear input/output wiring.',
    avoid: 'Dragging MAZos into low-level plumbing UI.',
    mazosMove: 'Use node-style thinking only for advanced loop diagrams.',
    loopPack: 'Loop Simulator',
  },
  {
    id: 'temporal',
    name: 'Temporal',
    category: 'workflow-automation',
    priority: 'copy-now',
    url: 'https://temporal.io/',
    repo: 'temporalio/temporal',
    plainEnglish: 'A durable workflow engine for long-running business processes.',
    whyItMatters: 'It is the clean reference for retries, durable state, signals, timeouts, and resumable work.',
    copy: 'Durable state, retries, timeouts, signals, and workflow history.',
    avoid: 'Enterprise workflow complexity before MAZos has a simple state model.',
    mazosMove: 'Define a loop state machine: draft, running, waiting, blocked, verified, retired.',
    loopPack: 'Loop State Machine',
  },
  {
    id: 'airflow',
    name: 'Apache Airflow',
    category: 'workflow-automation',
    priority: 'watch',
    url: 'https://airflow.apache.org/',
    repo: 'apache/airflow',
    plainEnglish: 'A scheduler and workflow orchestrator for data pipelines.',
    whyItMatters: 'It shows mature scheduling, dependencies, retries, and backfills.',
    copy: 'Dependency graph, run status, retries, and schedule visibility.',
    avoid: 'Data-engineering ceremony for product loops.',
    mazosMove: 'Borrow schedule clarity, not DAG complexity.',
    loopPack: 'Cadence Controller',
  },
  {
    id: 'prefect',
    name: 'Prefect',
    category: 'workflow-automation',
    priority: 'watch',
    url: 'https://www.prefect.io/',
    repo: 'PrefectHQ/prefect',
    plainEnglish: 'A workflow orchestration platform focused on observable data and automation flows.',
    whyItMatters: 'It makes failed runs, retries, and deployment state easy to inspect.',
    copy: 'Readable run states, deployment history, retries, and alerts.',
    avoid: 'Turning product research loops into data pipeline administration.',
    mazosMove: 'Add failed/stale/due statuses to every loop card.',
    loopPack: 'Loop Doctor',
  },
  {
    id: 'dagster',
    name: 'Dagster',
    category: 'workflow-automation',
    priority: 'watch',
    url: 'https://dagster.io/',
    repo: 'dagster-io/dagster',
    plainEnglish: 'A data orchestration platform built around assets, lineage, and runs.',
    whyItMatters: 'It is useful for thinking about evidence lineage and what output each run creates.',
    copy: 'Asset lineage, materialization history, and clear run artifacts.',
    avoid: 'Asset vocabulary unless MAZos users are tracking data products.',
    mazosMove: 'Show what artifact each loop produced and whether it changed a decision.',
    loopPack: 'Loop Receipts',
  },
  {
    id: 'kestra',
    name: 'Kestra',
    category: 'workflow-automation',
    priority: 'watch',
    url: 'https://kestra.io/',
    repo: 'kestra-io/kestra',
    plainEnglish: 'An event-driven orchestration platform with workflow definitions and execution monitoring.',
    whyItMatters: 'It is another strong example of readable execution histories and scheduled automation.',
    copy: 'Execution pages, task logs, schedules, and event triggers.',
    avoid: 'YAML-first UX for non-infrastructure loops.',
    mazosMove: 'Keep loop definitions readable in UI and exportable in repo.',
    loopPack: 'Runtime Export',
  },
  {
    id: 'dify',
    name: 'Dify',
    category: 'agent-builder',
    priority: 'copy-now',
    url: 'https://dify.ai/',
    repo: 'langgenius/dify',
    plainEnglish: 'An open-source platform for building AI apps, agents, workflows, and knowledge-backed assistants.',
    whyItMatters: 'It packages AI workflows into apps with logs, datasets, prompts, and operations.',
    copy: 'App packaging, workflow builder, run logs, datasets, and prompt operations.',
    avoid: 'Cloud-first AI app sprawl.',
    mazosMove: 'Make each MAZos loop feel like a small product with inputs, evidence, and outputs.',
    loopPack: 'Research Intelligence',
  },
  {
    id: 'langgraph',
    name: 'LangGraph',
    category: 'agent-builder',
    priority: 'copy-now',
    url: 'https://www.langchain.com/langgraph',
    repo: 'langchain-ai/langgraph',
    plainEnglish: 'A framework for stateful, controllable, multi-step agents.',
    whyItMatters: 'It is the strongest pattern source for pause/resume, interrupts, checkpoints, and state graphs.',
    copy: 'State graphs, checkpoints, interrupts, human review, and resumable runs.',
    avoid: 'Framework lock-in before MAZos owns its own loop contract.',
    mazosMove: 'Model loops as stateful runs with human checkpoints.',
    loopPack: 'Loop State Machine',
  },
  {
    id: 'flowise',
    name: 'Flowise',
    category: 'agent-builder',
    priority: 'study',
    url: 'https://flowiseai.com/',
    repo: 'FlowiseAI/Flowise',
    plainEnglish: 'A visual builder for LLM flows, chatbots, agents, and tool chains.',
    whyItMatters: 'It shows how non-coders expect to connect prompts, tools, memory, and outputs.',
    copy: 'Visual agent flow templates and quick testing.',
    avoid: 'Node soup that hides evidence and product decisions.',
    mazosMove: 'Use templates for common loops, but keep receipts as the main truth.',
    loopPack: 'Loop Templates',
  },
  {
    id: 'langflow',
    name: 'Langflow',
    category: 'agent-builder',
    priority: 'study',
    url: 'https://www.langflow.org/',
    repo: 'langflow-ai/langflow',
    plainEnglish: 'A visual framework for composing AI workflows and agents.',
    whyItMatters: 'It is useful for understanding how builders present components, variables, and tests.',
    copy: 'Component library, playground testing, and shareable flows.',
    avoid: 'Pretending visual composition replaces loop usefulness checks.',
    mazosMove: 'Add a simple loop draft preview with required evidence fields.',
    loopPack: 'Loop Factory',
  },
  {
    id: 'crewai',
    name: 'CrewAI',
    category: 'agent-builder',
    priority: 'study',
    url: 'https://www.crewai.com/',
    repo: 'crewAIInc/crewAI',
    plainEnglish: 'A framework and platform for coordinating role-based AI agents.',
    whyItMatters: 'It makes delegation, roles, tasks, and crew outputs explicit.',
    copy: 'Role definitions, task assignments, and output contracts.',
    avoid: 'Agent role theater without measurable output.',
    mazosMove: 'Tie every agent role to a receipt and a next decision.',
    loopPack: 'Agent Workbench',
  },
  {
    id: 'autogen',
    name: 'AutoGen',
    category: 'agent-builder',
    priority: 'study',
    url: 'https://microsoft.github.io/autogen/',
    repo: 'microsoft/autogen',
    plainEnglish: 'A Microsoft framework for building multi-agent conversations and workflows.',
    whyItMatters: 'It offers patterns for agent teams, tools, approvals, and conversations as execution traces.',
    copy: 'Agent conversation traces and tool-call visibility.',
    avoid: 'Chatty multi-agent loops that do not ship anything.',
    mazosMove: 'Summarize multi-agent work as verdict, evidence, blocker, and next action.',
    loopPack: 'Agent Workbench',
  },
  {
    id: 'llamaindex-workflows',
    name: 'LlamaIndex Workflows',
    category: 'agent-builder',
    priority: 'watch',
    url: 'https://www.llamaindex.ai/',
    repo: 'run-llama/llama_index',
    plainEnglish: 'A data and agent framework focused on knowledge-backed applications.',
    whyItMatters: 'It is strong where retrieval, tools, and structured agent steps meet.',
    copy: 'Knowledge ingestion, retrieval traces, and tool-backed workflows.',
    avoid: 'Turning MAZos into a generic RAG dashboard.',
    mazosMove: 'Use retrieval only when it changes the loop verdict.',
    loopPack: 'Research Intelligence',
  },
  {
    id: 'haystack',
    name: 'Haystack',
    category: 'agent-builder',
    priority: 'watch',
    url: 'https://haystack.deepset.ai/',
    repo: 'deepset-ai/haystack',
    plainEnglish: 'A framework for search, question answering, RAG, and AI pipelines.',
    whyItMatters: 'It offers practical pipeline ideas for source-grounded answers.',
    copy: 'Pipeline components, document stores, and evaluation hooks.',
    avoid: 'Research answers without product action.',
    mazosMove: 'Attach every research result to a suggested product move.',
    loopPack: 'Research Intelligence',
  },
  {
    id: 'codex',
    name: 'Codex',
    category: 'coding-agent',
    priority: 'copy-now',
    url: 'https://developers.openai.com/codex/',
    repo: 'openai/codex',
    plainEnglish: 'A coding agent workflow for tasks, code changes, reviews, and remote/local sessions.',
    whyItMatters: 'It is directly adjacent to MAZos because MAZos coordinates coding agents and verifies work.',
    copy: 'Task runs, worktree isolation, reviewable diffs, mobile/remote handoff, and automation hooks.',
    avoid: 'Letting remote mobile sessions execute local actions without review.',
    mazosMove: 'Use the remote snapshot plus intent queue as the mobile control layer.',
    loopPack: 'Remote MAZos',
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    category: 'coding-agent',
    priority: 'copy-now',
    url: 'https://www.anthropic.com/claude-code',
    plainEnglish: 'A terminal coding agent that edits, runs commands, and works inside a repo.',
    whyItMatters: 'It sets the baseline for command-line agent ergonomics and repo-native work.',
    copy: 'Terminal-first speed, compact context, command transparency, and repo-aware edits.',
    avoid: 'Hiding what the agent ran or changed.',
    mazosMove: 'Make MAZos show agent run receipts and branch state clearly.',
    loopPack: 'Agent Workbench',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'coding-agent',
    priority: 'study',
    url: 'https://www.cursor.com/',
    plainEnglish: 'An AI-native code editor focused on chat, edits, autocomplete, and codebase understanding.',
    whyItMatters: 'It shows how fast inline coding and project context can feel when the interface is focused.',
    copy: 'Fast context search, diff previews, and clear apply/reject flows.',
    avoid: 'Building another editor inside MAZos.',
    mazosMove: 'Send work to the best coding surface, then track receipts in MAZos.',
    loopPack: 'Runtime Router',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    category: 'coding-agent',
    priority: 'study',
    url: 'https://windsurf.com/',
    plainEnglish: 'An agentic code editor built around repo context and multi-step coding tasks.',
    whyItMatters: 'It is a strong reference for coding-agent UX, planning, and edit flow.',
    copy: 'Task-level planning, codebase context, and apply flow.',
    avoid: 'Conflating editor UX with operating-system UX.',
    mazosMove: 'Keep MAZos as the operator layer above coding tools.',
    loopPack: 'Runtime Router',
  },
  {
    id: 'cline',
    name: 'Cline',
    category: 'coding-agent',
    priority: 'copy-now',
    url: 'https://cline.bot/',
    repo: 'cline/cline',
    plainEnglish: 'An open-source coding agent extension with tool use, browser use, and file edits.',
    whyItMatters: 'It is a useful reference for approval loops and visible tool actions.',
    copy: 'Tool-call review, browser/file/shell visibility, and task checkpoints.',
    avoid: 'Approval fatigue on low-risk operations.',
    mazosMove: 'Use risk-based approvals for MAZos actions.',
    loopPack: 'Task Gate',
  },
  {
    id: 'roo-code',
    name: 'Roo Code',
    category: 'coding-agent',
    priority: 'study',
    url: 'https://roocode.com/',
    repo: 'RooVetGit/Roo-Code',
    plainEnglish: 'An open-source autonomous coding agent extension with modes and tool controls.',
    whyItMatters: 'It shows a mode-based approach to coding-agent behavior and permissions.',
    copy: 'Agent modes, permission controls, and explicit task handoff.',
    avoid: 'Too many modes without obvious user benefit.',
    mazosMove: 'Collapse agent choices into recommended runtime, reason, and risk.',
    loopPack: 'Runtime Router',
  },
  {
    id: 'aider',
    name: 'Aider',
    category: 'coding-agent',
    priority: 'copy-now',
    url: 'https://aider.chat/',
    repo: 'Aider-AI/aider',
    plainEnglish: 'A terminal pair-programming agent that edits code and commits through git.',
    whyItMatters: 'It is one of the clearest examples of git-native AI coding.',
    copy: 'Git-aware edits, commit discipline, concise terminal flow, and model flexibility.',
    avoid: 'Assuming every user wants terminal-only workflows.',
    mazosMove: 'Make branch, diff, commit, PR, and checks first-class in MAZos.',
    loopPack: 'PR Babysitter',
  },
  {
    id: 'continue',
    name: 'Continue',
    category: 'coding-agent',
    priority: 'watch',
    url: 'https://www.continue.dev/',
    repo: 'continuedev/continue',
    plainEnglish: 'An open-source AI coding assistant for IDEs with configurable models and context.',
    whyItMatters: 'It is a good reference for model/provider flexibility and context configuration.',
    copy: 'Provider flexibility, context providers, and team configuration.',
    avoid: 'Making model routing visible before the product outcome is clear.',
    mazosMove: 'Route tools by task and risk, not brand preference.',
    loopPack: 'Runtime Router',
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    category: 'coding-agent',
    priority: 'copy-now',
    url: 'https://www.all-hands.dev/',
    repo: 'All-Hands-AI/OpenHands',
    plainEnglish: 'An open-source software development agent with workspace, terminal, browser, and file context.',
    whyItMatters: 'It is close to the MAZos vision of agent work as inspectable workspace activity.',
    copy: 'Workspace session, action history, browser/shell visibility, and task replay.',
    avoid: 'Rebuilding an IDE when MAZos should coordinate tools.',
    mazosMove: 'Create an Agent Workbench summary above existing coding tools.',
    loopPack: 'Agent Workbench',
  },
  {
    id: 'opencode',
    name: 'opencode',
    category: 'coding-agent',
    priority: 'copy-now',
    url: 'https://opencode.ai/',
    repo: 'sst/opencode',
    plainEnglish: 'A terminal-native coding agent with session sharing and fast command UX.',
    whyItMatters: 'It is a strong reference for lightweight agent sessions and developer speed.',
    copy: 'Fast command UX, shareable sessions, and explicit project context.',
    avoid: 'Hiding verification behind smooth chat.',
    mazosMove: 'Track every agent session as a receipt with verification state.',
    loopPack: 'Runtime Export',
  },
  {
    id: 'devin',
    name: 'Devin',
    category: 'coding-agent',
    priority: 'study',
    url: 'https://www.cognition.ai/devin',
    plainEnglish: 'A commercial AI software engineer product for completing engineering tasks.',
    whyItMatters: 'It sets market expectations for delegated software work and autonomous task progress.',
    copy: 'Task progress, environment setup, status updates, and reviewable output.',
    avoid: 'Overpromising autonomy before verification is excellent.',
    mazosMove: 'Position MAZos as the verification and orchestration layer for agents.',
    loopPack: 'PR Babysitter',
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    category: 'coding-agent',
    priority: 'study',
    url: 'https://replit.com/ai',
    plainEnglish: 'An app-building agent inside Replit that creates and deploys software from prompts.',
    whyItMatters: 'It shows the appeal of prompt-to-running-app loops for non-specialist builders.',
    copy: 'Preview, deploy, fix loop, and plain progress updates.',
    avoid: 'Optimizing for toy apps when MAZos is for operating real projects.',
    mazosMove: 'Show project health and next shippable step, not just generated output.',
    loopPack: 'Shipping Spine',
  },
  {
    id: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    category: 'coding-agent',
    priority: 'watch',
    url: 'https://sourcegraph.com/cody',
    plainEnglish: 'An AI coding assistant with code search and enterprise codebase context.',
    whyItMatters: 'It is strong where large codebase context and search matter.',
    copy: 'Code search, references, and enterprise context retrieval.',
    avoid: 'Enterprise complexity in a personal command centre.',
    mazosMove: 'Make context packs small, explicit, and project-scoped.',
    loopPack: 'Context Map',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'research-knowledge',
    priority: 'study',
    url: 'https://www.perplexity.ai/',
    plainEnglish: 'An answer engine that searches the web and cites sources.',
    whyItMatters: 'It trains users to expect current, cited answers instead of vague summaries.',
    copy: 'Source citations, current web search posture, and concise answers.',
    avoid: 'Answer-only research with no product decision.',
    mazosMove: 'Every research item should end with copy/adapt/ignore and next build step.',
    loopPack: 'Research Intelligence',
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    category: 'research-knowledge',
    priority: 'study',
    url: 'https://notebooklm.google/',
    plainEnglish: 'A source-grounded notebook assistant for turning documents into answers and summaries.',
    whyItMatters: 'It is a simple reference for making a pile of sources usable.',
    copy: 'Source-grounded summaries, suggested questions, and briefing format.',
    avoid: 'Passive notes without action routing.',
    mazosMove: 'Turn saved research into build queues and loop prompts.',
    loopPack: 'Research Console',
  },
  {
    id: 'glean',
    name: 'Glean',
    category: 'research-knowledge',
    priority: 'watch',
    url: 'https://www.glean.com/',
    plainEnglish: 'An enterprise AI search and knowledge assistant.',
    whyItMatters: 'It shows what high-end workplace search looks like when connected across tools.',
    copy: 'Unified search, permission-aware results, and answer citations.',
    avoid: 'Enterprise search scope before MAZos has clean project boundaries.',
    mazosMove: 'Keep knowledge retrieval project-specific and permission-aware.',
    loopPack: 'Context Map',
  },
  {
    id: 'dust',
    name: 'Dust',
    category: 'research-knowledge',
    priority: 'study',
    url: 'https://dust.tt/',
    repo: 'dust-tt/dust',
    plainEnglish: 'A platform for building custom AI assistants connected to company knowledge and tools.',
    whyItMatters: 'It is a strong reference for assistant configuration, tool permissions, and knowledge connectors.',
    copy: 'Assistant catalog, tool permissions, and knowledge source selection.',
    avoid: 'Too many assistants with overlapping jobs.',
    mazosMove: 'Make agents purpose-bound and route tasks through one operator inbox.',
    loopPack: 'Agent Prep',
  },
  {
    id: 'mem',
    name: 'Mem',
    category: 'research-knowledge',
    priority: 'watch',
    url: 'https://mem.ai/',
    plainEnglish: 'An AI notes product focused on capturing and retrieving personal knowledge.',
    whyItMatters: 'It is a useful reminder that capture must be frictionless or users stop using it.',
    copy: 'Fast capture, automatic linking, and simple retrieval.',
    avoid: 'Letting memory become a junk drawer.',
    mazosMove: 'Save only decision-relevant research and receipts.',
    loopPack: 'Receipts',
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    category: 'research-knowledge',
    priority: 'copy-now',
    url: 'https://obsidian.md/',
    plainEnglish: 'A local-first knowledge base built around markdown files and links.',
    whyItMatters: 'It matches the local-first vault posture behind MAZos.',
    copy: 'Local files, markdown durability, backlinks, and user ownership.',
    avoid: 'Overloading the user with raw notes in the product surface.',
    mazosMove: 'Use the vault as source material, but show decisions and receipts in MAZos.',
    loopPack: 'Vault Handoff',
  },
  {
    id: 'langfuse',
    name: 'Langfuse',
    category: 'observability-evals',
    priority: 'copy-now',
    url: 'https://langfuse.com/',
    repo: 'langfuse/langfuse',
    plainEnglish: 'An open-source observability and evaluation platform for LLM applications.',
    whyItMatters: 'It makes prompts, traces, scores, costs, and evaluations inspectable.',
    copy: 'Traces, sessions, scores, datasets, and evaluation dashboards.',
    avoid: 'LLM metrics that do not change product behavior.',
    mazosMove: 'Score loops by usefulness, evidence, risk, and shipping impact.',
    loopPack: 'Loop Doctor',
  },
  {
    id: 'braintrust',
    name: 'Braintrust',
    category: 'observability-evals',
    priority: 'study',
    url: 'https://www.braintrust.dev/',
    plainEnglish: 'A platform for evaluating, logging, and improving AI products.',
    whyItMatters: 'It is a strong reference for datasets, experiments, evals, and prompt iteration.',
    copy: 'Experiment comparisons, eval datasets, and score tracking.',
    avoid: 'Eval bureaucracy before the product has clear success metrics.',
    mazosMove: 'Compare loop versions by whether they produced a useful next action.',
    loopPack: 'Loop Evals',
  },
  {
    id: 'helicone',
    name: 'Helicone',
    category: 'observability-evals',
    priority: 'watch',
    url: 'https://www.helicone.ai/',
    repo: 'Helicone/helicone',
    plainEnglish: 'An open-source observability platform for LLM requests, costs, and latency.',
    whyItMatters: 'It is a practical reference for costs, latency, caching, and request history.',
    copy: 'Request logs, cost tracking, latency, and cache visibility.',
    avoid: 'Cost dashboards detached from loop value.',
    mazosMove: 'Track loop cost only beside usefulness and evidence quality.',
    loopPack: 'Loop Evals',
  },
  {
    id: 'promptfoo',
    name: 'promptfoo',
    category: 'observability-evals',
    priority: 'copy-now',
    url: 'https://www.promptfoo.dev/',
    repo: 'promptfoo/promptfoo',
    plainEnglish: 'An open-source tool for testing and evaluating prompts and models.',
    whyItMatters: 'It gives MAZos a practical model for repo-backed tests of AI behavior.',
    copy: 'Prompt test cases, regression checks, and provider comparisons.',
    avoid: 'Testing prompts without connecting failures to product gates.',
    mazosMove: 'Add loop regression tests for important workflows.',
    loopPack: 'Loop Evals',
  },
  {
    id: 'phoenix',
    name: 'Arize Phoenix',
    category: 'observability-evals',
    priority: 'watch',
    url: 'https://phoenix.arize.com/',
    repo: 'Arize-ai/phoenix',
    plainEnglish: 'An open-source AI observability and evaluation tool.',
    whyItMatters: 'It is useful for tracing, experiments, and diagnosing AI application behavior.',
    copy: 'Trace inspection, experiments, and dataset-based evaluation.',
    avoid: 'Deep ML observability when MAZos needs operator clarity.',
    mazosMove: 'Use traces only when debugging a failed loop.',
    loopPack: 'Loop Evals',
  },
  {
    id: 'openllmetry',
    name: 'OpenLLMetry',
    category: 'observability-evals',
    priority: 'watch',
    url: 'https://www.traceloop.com/openllmetry',
    repo: 'traceloop/openllmetry',
    plainEnglish: 'OpenTelemetry-style tracing for LLM applications.',
    whyItMatters: 'It points toward standard trace formats instead of bespoke logs.',
    copy: 'Trace standards and tool-call observability.',
    avoid: 'Telemetry complexity before MAZos has simple receipts.',
    mazosMove: 'Keep receipts simple now, but make them exportable later.',
    loopPack: 'Runtime Export',
  },
  {
    id: 'humanloop',
    name: 'Humanloop',
    category: 'observability-evals',
    priority: 'study',
    url: 'https://humanloop.com/',
    plainEnglish: 'A platform for prompt management, evaluation, and human feedback.',
    whyItMatters: 'It shows how human review and scoring can improve AI workflows.',
    copy: 'Human feedback, prompt versioning, and eval workflows.',
    avoid: 'Feedback widgets that do not feed a next action.',
    mazosMove: 'Let users mark a loop receipt as useful, noisy, blocked, or retired.',
    loopPack: 'Loop Doctor',
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'product-ops',
    priority: 'copy-now',
    url: 'https://linear.app/',
    plainEnglish: 'A fast issue tracker and product planning tool built around focus and momentum.',
    whyItMatters: 'It is a benchmark for low-clutter product operations UX.',
    copy: 'Fast command menu, clean issue states, cycles, priorities, and focused lists.',
    avoid: 'Turning MAZos into another ticket tracker.',
    mazosMove: 'Use one operator inbox with clear states and next actions.',
    loopPack: 'Operator Inbox',
  },
  {
    id: 'github-projects',
    name: 'GitHub Projects',
    category: 'product-ops',
    priority: 'study',
    url: 'https://github.com/features/issues',
    plainEnglish: 'GitHub-native issues, projects, branches, PRs, and checks.',
    whyItMatters: 'It is the repo source of truth for coding-agent work and verification.',
    copy: 'PR checks, issue links, branch state, and review workflow.',
    avoid: 'Duplicating GitHub data without adding operator decisions.',
    mazosMove: 'Show current branch, PR, CI, and next action in one product card.',
    loopPack: 'PR Babysitter',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'product-ops',
    priority: 'study',
    url: 'https://www.notion.com/',
    plainEnglish: 'A flexible workspace for docs, databases, notes, and lightweight project management.',
    whyItMatters: 'It proves people value flexible capture, but also shows how clutter grows.',
    copy: 'Flexible docs/databases, templates, and human-readable project pages.',
    avoid: 'Dashboard sprawl and decorative databases.',
    mazosMove: 'Keep MAZos surfaces opinionated: today, inbox, loops, research, system.',
    loopPack: 'Declutter',
  },
  {
    id: 'height',
    name: 'Height',
    category: 'product-ops',
    priority: 'watch',
    url: 'https://height.app/',
    plainEnglish: 'An autonomous project management tool with AI-assisted task handling.',
    whyItMatters: 'It shows how product ops tools are moving toward AI-managed work queues.',
    copy: 'AI-assisted task updates and project awareness.',
    avoid: 'Autonomous task churn without verification.',
    mazosMove: 'Queue remote intents, then verify locally before action.',
    loopPack: 'Remote MAZos',
  },
  {
    id: 'motion',
    name: 'Motion',
    category: 'product-ops',
    priority: 'watch',
    url: 'https://www.usemotion.com/',
    plainEnglish: 'An AI scheduling and task planning product.',
    whyItMatters: 'It is useful for thinking about cadence, time blocking, and what is due next.',
    copy: 'Due dates, automatic scheduling, and priority surfacing.',
    avoid: 'Calendar obsession inside a product command centre.',
    mazosMove: 'Show which loops are due, stale, blocked, or retired.',
    loopPack: 'Cadence Controller',
  },
  {
    id: 'asana',
    name: 'Asana',
    category: 'product-ops',
    priority: 'watch',
    url: 'https://asana.com/',
    plainEnglish: 'A work management platform for teams, projects, dependencies, and reporting.',
    whyItMatters: 'It is a mature example of portfolios, dependencies, and project health.',
    copy: 'Project health, dependencies, and status updates.',
    avoid: 'Team-management overhead for a solo/operator command centre.',
    mazosMove: 'Use project health summaries without heavy task hierarchy.',
    loopPack: 'Shipping Spine',
  },
  {
    id: 'monday',
    name: 'monday.com',
    category: 'product-ops',
    priority: 'watch',
    url: 'https://monday.com/',
    plainEnglish: 'A configurable work management platform with boards, automations, and dashboards.',
    whyItMatters: 'It shows the commercial demand for customizable operations surfaces.',
    copy: 'Status boards, automation recipes, and dashboard summaries.',
    avoid: 'Colorful generic boards with no opinion about what matters.',
    mazosMove: 'Keep the UI opinionated around shipping and loop usefulness.',
    loopPack: 'Declutter',
  },
];

export function buildMassCompetitorCatalog(): MassCompetitorCatalog {
  const groups = (Object.keys(CATEGORY_COPY) as MassCompetitorCategory[]).map((category) => ({
    category,
    ...CATEGORY_COPY[category],
    competitors: MASS_COMPETITORS.filter((competitor) => competitor.category === category),
  }));

  return {
    generatedAt: new Date().toISOString(),
    sourceRule: 'Simple mass list: use official product/docs pages and GitHub repos where available; verify latest pushed_at/stars through the live Competitor Radar before copying deeply.',
    total: MASS_COMPETITORS.length,
    copyNow: MASS_COMPETITORS.filter((competitor) => competitor.priority === 'copy-now').length,
    groups,
    topMoves: [
      'Build Run Inspector from Loop Receipts: every agent/research loop needs trigger, steps, evidence, failure, and next action.',
      'Build Operator Inbox: one place to accept, defer, dismiss, or send competitor/research findings into Task Gate.',
      'Build Cadence Controller: show due, stale, blocked, useful, retired loops instead of making users inspect dashboards.',
      'Build Agent Workbench: summarize branch, diff, command, browser, receipt, CI, and PR state across Codex/Claude/OpenCode-style tools.',
      'Build Loop Evals: score loops by usefulness, evidence, risk, cost, and shipping impact before adding more automation.',
    ],
  };
}
